# Generated by Django 3.2.4 on 2021-07-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('phno', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
